// Products Constants

export const ALL_PRODUCT_REQUEST = " ALL_PRODUCT_REQUEST";
export const ALL_PORDUCT_SUCCESS = "ALL_PORDUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

// Order Constants

export const PRODUCT_DETAILS_REQUEST = "ALL_PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "ALL_PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "ALL_PRODUCT_DETAILS_FAIL";

// Clear
export const CLEAR_ERRORS = " CLEAR_ERRORS";
