export const ALL_PRODUCT_REQUEST = " ALL_PRODUCT_REQUEST";
export const ALL_PORDUCT_SUCCESS = "ALL_PORDUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS = " CLEAR_ERRORS";
